version: "3.8"
services:
  radio:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/media:/srv/apps/radiocolloc/media
      - ./data/runtime:/srv/apps/radiocolloc/runtime
    restart: unless-stopped
